# Generated by Django 4.1.2 on 2022-10-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_resulttest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtype', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('maxballs', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='question',
            name='testnumb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.test'),
            preserve_default=False,
        ),
    ]
