# Generated by Django 4.1.2 on 2022-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_test_remove_question_pub_date_delete_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
