# Generated by Django 4.1.2 on 2022-10-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choice_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(verbose_name='Правильный ответ'),
        ),
    ]
