# Generated by Django 4.1.2 on 2022-10-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_question_queue_resulttest_test_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttest',
            name='test_done',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.test'),
        ),
    ]
